rosbag:
  input_bag_path: '/path/to/input_bag_file'
  output_bag_path: '/path/to/output_bag_file'
  output_save_compressed_image: True
  output_storage_id: 'sqlite3' # 'sqlite3' or 'mcap'
yolo:
  model: './yolo11x_anonymizer.pt'
  config_path: './yolo_config.yaml'
  confidence: 0.15
segment_anything_2:
  model_cfg: 'configs/sam2.1/sam2.1_hiera_s.yaml'
  checkpoint_path: './sam2.1_hiera_small.pt'
blur:
  kernel_size: 31
  sigma_x: 9